Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13485): Gdk-CRITICAL **: 09:30:08.300: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13555): Gdk-CRITICAL **: 09:30:08.452: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:13517): Gdk-CRITICAL **: 09:30:08.453: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13489): Gdk-CRITICAL **: 09:30:08.486: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13530): Gdk-CRITICAL **: 09:30:08.507: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13596): Gdk-CRITICAL **: 09:30:08.582: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13568): Gdk-CRITICAL **: 09:30:08.630: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13626): Gdk-CRITICAL **: 09:30:08.676: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13610): Gdk-CRITICAL **: 09:30:08.705: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13637): Gdk-CRITICAL **: 09:30:08.724: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...........................................................................................
[4726 9515]
.
[9529 4689]
.
[9247 4804]
.
[9768 4571]
.
[9457 4732]
.
[7850 5722]
.
[9728 4592]
.
[7480 5914]
..
[8578 5170]
.
[6559 6783]
..............................................................................
[2302 9011]
.
[9087 2194]
...........
[9491 2121]
.
[8469 2393]
..
[8982 2257]
...
[9507 2152]
..........
[7401 2761]
.
[6107 3389]
.
[5347 3689]
.
[4136 4846]
...................................................
[1166 8525]
....
[8607 1112]
.......................
[9220 1049]
....
[7540 1277]
.
[8425 1134]
...
[9270 1047]
......................
[6245 1512]
.....
[4519 2149]
....
[3793 2396]
.
[2670 3496]
.............
[ 602 8036]
.....
[8161  586]
...................................
[8966  542]
..........
[7797  592]
..
[9018  525]
.
[6515  695]
.......................
[ 332 7540]
...
[7712  337]
..............
[5103  883]
..............
[3358 1367]
.....
[2646 1560]
.
[1709 2506]
....................
[8709  280]
.........
[ 193 6986]
......
[7045  342]
..
[8756  285]
....
[7225  202]
......
[5353  407]
.............................................
[ 132 6488]
..............
[6750  132]
......
[8453  156]
..
[4087  557]
...................
[1146 1839]
.
[1854 1063]
.
[2452  886]
...
[8439  162]
....
[6240  216]
.......
[  88 5983]
................
[6284   98]
..
[4233  249]
...................................
[  65 5441]
.......
[8222   98]
..............
[5792   74]
.......................
[  55 4955]
...
[8112  100]
............
[3206  370]
..
[5331  145]
...........
[5341   57]
..
[ 777 1303]
.....
[1285  767]
......
[  48 4448]
.
[1766  584]
..........................
[3199  174]
.....
[  47 3924]
.
[7999   61]
......
[4850   43]
................/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......................
[4361   36]
..............
[7783   70]
...........
[3868   35]
.............
[4420  101]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.............
[7724   53]
...
[540 928]
.
[2436  255]
...
[935 563]
.............
[1290  399]
..
[2377  132]
.......................
[7377   42]
...............
[7482   40]
...
[3590   83]
..................
[368 689]
...........
[666 418]
.......
[1826  188]
...........
[1704  101]
...
[952 280]
....
[7242   31]
..
[6902   29]
.............................
[2814   70]
............
[272 514]
...........
[495 315]
.....
[6969   21]
...................
[1244   83]
.
[1398  129]
.....
[6372   21]
.......
[686 209]
........................
[6718   20]
.
[2180   62]
.
[195 385]
.................
[364 246]
.................................
[6473   17]
.
[5758   14]
.
[898  70]
.............
[498 169]
.
[1060   95]
...
[154 296]
......................
[276 196]
.
[1711   49]
............
[6229   16]
..........................
[123 233]
..............
[660  53]
...
[5151   11]
............
[5957   13]
.
[377 131]
......
[212 162]
........
[811  75]
.........
[104 193]
..............
[1309   41]
...................
[5686   12]
........
[ 86 160]
............
[160 125]
.........
[498  45]
..........
[ 71 134]
..............
[4515    7]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[280 102]
..
[5431   12]
.................
[136 104]
....
[616  66]
...............
[1013   35]
.......
[5196   12]
...........
[112  85]
.....
[387  35]
.........................
[93 74]
.....
[221  85]
...
[4942   11]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..........
[3952    6]
..............
[4646   11]
.......
[310  31]
.
[488  54]
...
[766  28]
....................
[4395   11]
.
[175  67]
...........................
[4098   11]
.......
[235  25]
....................
[3844   11]
.........
[3364    5]
..
[143  59]
...
[591  24]
.....
[370  40]
....
[3601   11]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[192  23]
....................
[113  50]
..........
[142  20]
........................
[87 46]
.
[471  23]
....
[118  19]
..
[289  39]
.......................
[104  19]
.
[71 39]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[2806    4]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
............
[378  20]
....
[231  36]
......................
[301  19]
...
[2323    4]
..
[191  32]
..................
[250  18]
......
[164  31]
..................
[215  18]
......
[145  27]
............
[1891    4]
......
[193  17]
....
[113  26]
....................
[164  16]
.
[100  26]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[1540    3]
..........
[1235    3]
..........
[981   3]
..........
[796   2]
..........
[651   2]
..........
[524   2]
..........
[423   2]
..........
[350   2]
..........
[302   2]
..........
[260   2]
..........
[210   2]
..........
[178   2]
..........
[155   2]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
No 1 6
Done
