Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367428): Gdk-CRITICAL **: 09:29:43.524: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367433): Gdk-CRITICAL **: 09:29:43.544: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367459): Gdk-CRITICAL **: 09:29:43.651: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367470): Gdk-CRITICAL **: 09:29:43.653: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367494): Gdk-CRITICAL **: 09:29:43.671: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367524): Gdk-CRITICAL **: 09:29:43.738: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367537): Gdk-CRITICAL **: 09:29:43.768: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367558): Gdk-CRITICAL **: 09:29:43.791: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367572): Gdk-CRITICAL **: 09:29:43.798: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367584): Gdk-CRITICAL **: 09:29:43.842: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.........................................................................
[4732 9578]
.
[4642 9601]
.
[4714 9608]
.
[4689 9566]
.
[4686 9599]
.
[4723 9574]
.
[4679 9620]
.
[4620 9615]
.........................................................................
[2271 9167]
.
[2263 9208]
.
[2269 9179]
.
[2271 9204]
.
[2269 9181]
.
[2280 9146]
.
[2268 9230]
.
[2220 9216]
.........................................................................
[1112 8767]
.
[1100 8776]
.
[1098 8798]
.
[1151 8800]
.
[1129 8803]
.
[1124 8836]
.
[1110 8814]
.
[1109 8711]
.........................................................................
[ 576 8325]
.
[ 592 8356]
.
[ 559 8375]
.
[ 593 8384]
.
[ 603 8433]
.
[ 597 8386]
.
[ 615 8424]
..
[ 586 8135]
......................................................................
[ 320 7883]
..
[ 331 7921]
.
[ 309 7985]
.
[ 341 7993]
.
[ 326 7991]
.
[ 329 8031]
..
[ 341 7991]
..........
[ 353 7018]
.......................................................
[ 188 7423]
...
[ 197 7482]
......
[ 188 7566]
.
[ 197 7564]
..
[ 204 7630]
.
[ 186 7568]
.
[ 215 7519]
........................................
[ 262 5166]
...................
[ 127 7027]
.......
[ 122 7011]
....
[ 112 7148]
..
[ 116 7136]
...
[ 130 7108]
.
[ 132 7203]
..
[ 120 7102]
......................................................
[  86 6634]
............
[  80 6519]
.
[  64 6709]
.
[  72 6642]
..
[  90 6651]
.
[  95 6758]
...........
[  83 6600]
........................
[ 209 3401]
....................
[  66 6221]
.........
[  49 6278]
...
[  57 5942]
......
[  52 6097]
.
[  71 6268]
....
[  68 6129]
...................
[  60 6053]
........................
[  56 5781]
..............
[  37 5877]
...........
[  40 5274]
.
[  54 5551]
.
[  47 5008]
..........
[  58 5444]
...................
[  49 5360]
...
[  52 5283]
..............
[  35 5420]
............................
[  44 4901]
.......
[  47 4388]
.....
[  36 4133]
........
[  42 3652]
...
[  32 5015]
...
[  52 4414]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[ 162 2114]
......................
[  48 4222]
....
[  32 4613]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........................
[  45 2942]
...
[  34 2837]
...
[  50 3215]
..........
[  39 2398]
......
[  44 3007]
.................................
[  30 1880]
.
[  46 2155]
....
[  44 1833]
.............
[  42 2032]
.....
[  37 1529]
.............
[ 138 1324]
..........
[  44 1386]
....
[  30 1219]
..................
[  43 1135]
.
[  41 1338]
.................
[ 37 963]
......
[ 42 920]
........
[ 29 821]
.................
[ 39 884]
................
[ 40 741]
....
[ 41 638]
.............
[ 27 558]
...
[ 37 640]
.......
[ 37 645]
.....................
[ 39 494]
.................
[ 26 423]
.
[ 33 511]
............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[ 32 425]

Data Dump...

[ 39 530]
.
[108 823]
..........
[ 35 453]
..
[ 23 354]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.............
[ 37 397]
...
[ 31 347]
....................
[ 31 288]
.
[ 35 324]
.................
[ 26 260]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[ 29 285]
............
[ 28 266]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[ 98 540]
..........
[ 86 350]
..........
[ 77 241]
..........
[ 72 183]
..........
[ 67 132]
..........
[ 61 106]
..........
[58 89]
..........
[52 72]
..........
[47 66]
..........
[45 61]
..........
[41 52]
..........
[39 50]
..........
[37 47]
..........
[33 43]
..........
[33 40]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
High 1 5
Done
