Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122347): Gdk-CRITICAL **: 01:01:08.812: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122356): Gdk-CRITICAL **: 01:01:08.860: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122432): Gdk-CRITICAL **: 01:01:08.966: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122392): Gdk-CRITICAL **: 01:01:08.998: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122448): Gdk-CRITICAL **: 01:01:09.020: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122377): Gdk-CRITICAL **: 01:01:09.034: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122473): Gdk-CRITICAL **: 01:01:09.094: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122528): Gdk-CRITICAL **: 01:01:09.190: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122494): Gdk-CRITICAL **: 01:01:09.208: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122515): Gdk-CRITICAL **: 01:01:09.227: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[9554 4610]
.
[8529 5226]
.
[8894 5029]
.
[5161 8612]
.
[7490 5984]
.
[6338 7025]
.
[9677 4577]
.
[9445 4691]
.
[8685 5089]
............................................................................
[9117 2142]
....
[7698 2648]
...
[6942 2879]
...
[9403 2166]
.
[8956 2341]
.
[2917 6882]
..
[7545 2656]
...
[5288 3764]
.
[3895 5103]
..............................................................
[8706 1067]
..............
[6393 1469]
.
[9155 1059]
.
[8400 1162]
...
[5289 1700]
...
[1751 5174]
........
[6345 1428]
......
[2416 3724]
..
[3614 2514]
..................................
[8241  531]
.........................
[8833  587]
..
[7828  616]
....
[5089  879]
...........
[3885 1069]
......
[1131 3775]
......
[5225  803]
............
[1570 2673]
..
[2448 1720]
...
[7798  302]
..................................
[8489  316]
.....
[7226  350]
...............
[3851  581]
.........
[7286  191]
......
[2755  724]
.........
[ 731 2681]
.......
[4218  507]
............
[1063 1947]
.....
[1648 1230]
..............
[8156  188]
.......
[6538  213]
..
[6831  116]
...........................
[2862  386]
................
[1914  512]
............
[ 512 1881]
...
[6370   72]
.....
[3305  332]
........
[7765  123]
..
[ 729 1418]
......
[1151  902]
.........
[5759  133]
.......................
[5913   57]
...............
[2099  290]
...............
[1327  367]
...............
[ 363 1311]
...
[7375   76]
.....
[5455   43]
.......
[ 493 1038]
...
[2499  215]
.........
[769 674]
......
[4969   79]
.......................
[4992   25]
............
[1528  219]
................
[941 269]
............
[6897   53]
...
[4552   20]
..
[273 876]
.........
[361 740]
...................
[535 484]
.........
[1915  146]
..
[4069   17]
........
[4264   54]
..........................
[3606   16]
.
[1096  166]
.................
[644 211]
.........
[6407   40]
...
[3129   16]
.....
[266 536]
.......
[203 615]
..............
[2653   16]
.............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[385 375]
.........................
[1427  101]
.
[3527   42]
.......
[782 130]
......
[460 165]
..
[189 391]
...........
[5919   28]
........
[150 450]
...................
[285 283]
....................
[142 291]
............
[316 128]
..
[555 103]
..............
[1071   75]
..
[2898   32]
.............
[116 329]
....
[5393   20]
......
[115 223]
....
[209 220]
.....................
[236 103]
................
[ 91 174]
.........
[403  84]
.......................
[ 78 135]
..
[ 99 254]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[165 168]
.....
[174  88]
..............
[795  61]
......
[2331   27]
..........
[4806   17]
.......
[146  69]
...
[312  71]
..........
[123 136]
.....
[ 83 204]
............
[110  58]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..................
[ 99 107]
.............
[242  59]
.
[ 73 163]
.............
[81 83]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
............
[591  52]
....
[ 65 123]
.........
[4231   13]
.
[192  55]
.....
[1878   25]
.....
[54 92]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.............
[150  47]
............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[109  42]

Data Dump...
..........
[456  45]
.......
[3635   12]
.....
[1496   22]
..............
[357  37]
...............
[3093   11]
......
[1207   20]
..
[269  34]
....................
[222  30]
...........
[2630   10]
.......
[167  29]
.
[950  19]
................
[136  28]
...............
[109  27]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[2205    8]
...
[742  17]
..................
[1813    8]
.
[570  17]
..................
[456  16]
....
[1520    8]
.............
[373  15]
...........
[1247    7]
......
[316  14]
................
[275  14]
.....
[1026    7]
..........
[229  13]
..............
[186  13]
.........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[820   7]
..........
[663   6]
..........
[538   6]
..........
[427   6]
..........
[341   6]
..........
[292   6]
..........
[235   6]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
No 1 7
Done
