Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121880): Gdk-CRITICAL **: 01:01:00.603: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121888): Gdk-CRITICAL **: 01:01:00.623: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121917): Gdk-CRITICAL **: 01:01:00.699: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121900): Gdk-CRITICAL **: 01:01:00.718: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121943): Gdk-CRITICAL **: 01:01:00.745: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121959): Gdk-CRITICAL **: 01:01:00.795: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121972): Gdk-CRITICAL **: 01:01:00.832: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122016): Gdk-CRITICAL **: 01:01:00.893: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122006): Gdk-CRITICAL **: 01:01:00.926: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121989): Gdk-CRITICAL **: 01:01:00.969: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4655 9237]
.
[4700 9272]
.
[4801 9274]
.
[4751 9260]
.
[4680 9327]
.
[4682 9275]
.
[4706 9326]
.
[4706 9144]
.
[5726 7684]
...............................................................................
[2248 8452]
.
[2350 8544]
..
[2338 8484]
.
[2310 8568]
.
[2274 8632]
.
[2276 8648]
.
[2244 8533]
......
[2528 7544]
...............
[4207 4605]
..........................................................
[1144 7713]
.
[1215 7759]
.
[1164 7778]
.
[1164 7895]
..
[1197 7402]
.
[1136 7747]
.
[1100 7970]
....................
[1545 5588]
............................................
[3277 2662]
.........
[ 593 6938]
.
[ 649 7009]
.....
[ 630 7109]
.
[ 657 6923]
....
[ 577 7237]
.
[ 618 6877]
.......
[ 686 5866]
.............................................
[1055 3777]
...............
[ 381 6238]
..
[ 347 6096]
..
[ 368 6350]
........
[ 385 6014]
..
[ 307 6497]
..
[ 344 5951]
..........................
[ 443 4251]
...........
[2631 1522]
....................
[ 217 5485]
......
[ 230 5606]
.
[ 198 5149]
...........
[ 179 5701]
.
[ 255 5064]
.........
[ 205 5006]
.................
[ 769 2483]
......................
[ 140 4721]
..........
[ 157 4828]
......
[ 341 2831]
..
[ 134 4196]
........
[ 114 4918]
...........
[ 145 4075]
............
[ 125 4050]
.................
[  92 4028]
..........
[ 108 4076]
..
[2101  907]
.....................
[  77 4131]
..
[  84 3218]
........................
[ 104 3161]
.
[  74 3257]
.....
[ 580 1599]
........
[  79 3289]
.
[  95 3141]
............
[ 268 1836]
...................
[  61 3345]
............
[  51 2505]
.
[  64 2301]
..............
[  60 2526]
.................
[  77 2341]
..................
[  70 2336]
..
[  50 2589]
..
[  45 1791]
...............
[  53 1776]
..........................
[  48 1607]
....
[  44 1045]
................
[  43 1822]
.
[1681  554]
...
[  45 1002]
..............
[  62 1699]
.....
[ 44 249]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...........
[ 220 1226]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[ 44 188]

Data Dump...
.
[  61 1632]
........
[ 447 1040]
.
[  38 1083]
...............
[  42 1105]
.............
[ 35 315]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[  55 1147]
..........
[  50 1105]
..............
[ 37 711]
..........
[ 45 649]
...................
[ 41 686]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[ 39 129]

Data Dump...
..
[ 34 385]
.........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[ 38 266]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[175 815]
....
[1381  363]
..
[357 697]
...................
[146 542]
..........
[288 472]
.......
[1139  240]
.........
[118 376]
.............
[225 329]
..........
[101 275]
..........
[921 165]
...........
[186 234]
.
[ 83 198]
....................
[ 71 159]
............
[154 183]
......
[ 58 128]
...
[746 110]
.............
[49 85]
.........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[121 141]
..............
[ 99 113]
.........
[604  76]
....
[82 91]
.............
[66 72]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[508  61]
..........
[409  49]
..........
[332  42]
..........
[278  37]
..........
[232  34]
..........
[190  33]
..........
[158  29]
..........
[122  27]
..........
[97 24]
..........
[69 19]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
Low 1 9
Done
