Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:12986): Gdk-CRITICAL **: 09:29:56.046: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13013): Gdk-CRITICAL **: 09:29:56.121: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:12988): Gdk-CRITICAL **: 09:29:56.177: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13040): Gdk-CRITICAL **: 09:29:56.209: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:13023): Gdk-CRITICAL **: 09:29:56.245: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13066): Gdk-CRITICAL **: 09:29:56.298: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13045): Gdk-CRITICAL **: 09:29:56.307: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13090): Gdk-CRITICAL **: 09:29:56.315: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13072): Gdk-CRITICAL **: 09:29:56.321: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13097): Gdk-CRITICAL **: 09:29:56.441: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.................................................................................
[4681 9452]
..
[4735 9462]
.
[4718 9409]
.
[4662 9473]
.
[4678 9441]
.
[5009 8961]
.
[7729 5776]
.
[6351 6960]
......
[7803 5656]
....................................................................
[2275 8845]
...
[2295 8874]
.
[2249 8833]
.
[2256 8890]
.
[2240 8923]
..........
[2967 6900]
.............
[5849 3430]
...
[6594 3002]
...
[5088 3956]
.............................................
[1125 8250]
...
[1146 8330]
.
[1108 8243]
.
[1148 8334]
.
[1133 8261]
..................................
[1954 4734]
....................
[4264 2118]
........
[5606 1594]
........
[4117 2192]
.
[ 577 7719]
..
[ 628 7775]
.
[ 628 7762]
.
[ 596 7626]
.
[ 595 7670]
....................................................................
[ 332 7075]
.
[ 370 7144]
..
[ 351 7166]
.
[ 343 6978]
.
[ 312 7033]
......
[1367 3056]
.....................
[3086 1380]
..........
[4683  928]
...................
[3402 1274]
........
[ 186 6397]
....
[ 219 6561]
.
[ 219 6500]
...
[ 192 6413]
..
[ 200 6312]
............................................................
[ 120 5711]
.
[ 150 5935]
.
[ 137 5905]
....
[ 116 5752]
....
[1004 1969]
..
[ 131 5579]
...................
[2228  905]
...................
[3837  537]
..............
[ 102 5241]
....
[ 103 5273]
.
[  91 4955]
...
[  79 5037]
...........
[2843  727]
...
[  97 4735]
.........................................
[  75 4463]
...
[  83 4597]
.....
[  63 4098]
...
[  60 4283]
.....................
[  86 3804]
.................
[ 750 1253]
..........
[  60 3671]
..
[  61 3813]
........
[1628  603]
....
[  50 3483]
..
[  52 3219]
.......................
[3098  333]
..............
[  72 2840]
..
[  53 2866]
.......
[  52 2856]
...........
[  42 2686]
........
[  43 2455]
............
[2321  462]
...............
[  42 2076]
................
[  50 2021]
.....
[  37 1978]
......
[  66 1989]
...........
[  39 1763]
.........
[  38 1456]
............................
[  33 1400]
.......
[  35 1046]
......
[  49 1378]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[586 837]
......
[  38 1245]
.......
[1165  421]
..
[ 31 984]
..
[  60 1398]
................/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..............
[ 43 960]
.
[ 35 865]
................
[2493  223]
........
[ 29 631]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[ 55 984]
....
[ 42 687]
.......................
[ 38 548]
........
[ 50 692]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[1891  305]
...........
[ 42 509]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[456 560]
..
[845 290]
...............
[2013  153]
................
[1557  200]
...
[630 221]
...
[352 379]
....................
[1598  102]
............
[472 165]
.....
[282 271]
...
[1294  146]
........................
[365 140]
..
[1279   73]
..........
[235 195]
..............
[1045   99]
......
[278 109]
.................
[193 147]
.
[1035   57]
.........
[210  86]
.......................
[874  71]
..
[157  76]
......
[167 106]
...............
[119  68]
...
[808  41]
................
[104  63]
..............
[82 47]
.
[135  83]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...........
[708  52]
........
[107  67]
..
[635  31]
..................
[85 52]
..................
[579  42]
.
[72 49]
...
[521  23]
............
[58 40]
................
[47 36]
............/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[44 31]

Data Dump...
......
[415  18]
.
[465  35]
.................
[343  17]
......
[388  29]
............
[275  15]
...........
[326  24]
......
[223  14]
................
[189  11]
...
[272  20]
.............
[167  11]
...............
[143   9]
.
[216  17]
..............
[117   6]
.............
[93  4]
..........
[197  13]
...
[74  4]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[166  12]
..........
[143  11]
..........
[120   8]
..........
[103   7]
..........
[85  7]
..........
[69  6]
..........
[56  4]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
Low 1 7
Done
