Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13502): Gdk-CRITICAL **: 09:30:08.191: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13504): Gdk-CRITICAL **: 09:30:08.208: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13542): Gdk-CRITICAL **: 09:30:08.239: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13521): Gdk-CRITICAL **: 09:30:08.274: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13560): Gdk-CRITICAL **: 09:30:08.331: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13575): Gdk-CRITICAL **: 09:30:08.344: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13612): Gdk-CRITICAL **: 09:30:08.375: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13599): Gdk-CRITICAL **: 09:30:08.407: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13629): Gdk-CRITICAL **: 09:30:08.426: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13638): Gdk-CRITICAL **: 09:30:08.497: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[9999 4676]
.
[8390 5660]
.
[9539 4878]
.
[9689 4782]
.
[5562 8398]
.
[8822 5291]
.
[9985 4528]
.
[9482 4814]
.
[6801 6932]
............................................................................
[9999 2193]
.....
[8918 2506]
.
[9401 2363]
..
[9981 2096]
...
[9110 2310]
.
[6415 3530]
.
[7495 2912]
....
[3255 6699]
..
[4426 5015]
...........................................................
[9999 1082]
..........
[9971 1047]
.
[9005 1230]
...
[8057 1342]
.......
[8629 1184]
............
[6007 1768]
....
[4573 2439]
...
[2036 5066]
.........
[2909 3732]
.......................
[9999  560]
................
[9950  558]
.....
[8422  655]
...........
[6950  791]
....
[8044  660]
..............................
[4596 1140]
.
[9999  302]
...
[3184 1715]
...
[1401 3748]
............
[1968 2779]
.....
[9930  298]
...............
[7613  390]
....................
[5627  495]
...
[7282  363]
..
[9999  182]
................................
[9896  162]
...........
[3487  759]
......
[2165 1277]
.
[ 989 2705]
........
[9999  115]
.....
[1309 2068]
.
[6653  250]
.............................
[6427  233]
.
[4384  341]
.......
[9859  105]
............
[9999   71]
.........................................
[2536  546]
....
[5646  171]
.
[1470  956]
....
[ 730 1918]
..
[9999   47]
....
[9808   70]
....
[ 890 1545]
....................
[5510  148]
......
[3275  261]
................
[9999   35]
.....................
[9733   51]
........................
[9999   24]
.
[4600  125]
.......
[1827  405]
....
[1020  711]
....
[ 560 1337]
..........
[ 618 1155]
...............
[4580   97]
...
[9999   21]
.
[9599   33]
..
[2359  198]
.....................................
[9999   17]
...........................
[3654  102]
.....
[9401   29]
....
[9999   15]
.......
[1316  312]
..
[707 551]
.....
[429 954]
..........
[434 891]
.......
[9999   14]
..........
[3746   69]
.....
[1704  153]
................
[9999   11]
...............
[9054   24]
.........
[9999   11]
..........................
[9999   11]
.............
[2796   82]
......
[9999   11]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..........
[495 422]
..
[921 254]
.
[338 688]
.....
[314 686]
.......
[8549   17]
........
[2997   47]
....
[1209  115]
.............................................
[7853   13]
.
[2134   71]
...........
[360 340]
.
[246 501]
...
[682 197]
...
[240 498]
....................
[2349   40]
.
[883  97]
....................
[6968   12]
...........................
[1599   62]
.....
[277 274]
....
[198 374]
..
[181 386]
...
[508 155]
.....................
[5910   11]
...
[651  82]
.......
[1822   28]
......................................
[216 214]
..
[145 306]
.
[1201   54]
.
[162 287]
............
[385 127]
...
[4830    9]
...................
[471  67]
...............
[1440   24]
.....................
[171 183]
...
[110 234]
......
[139 223]
........
[916  45]
.....
[3827    8]
....
[282 102]
......................
[335  58]
.....................
[ 93 194]
..
[133 147]
...
[1134   20]
.........
[118 169]
......................
[2965    7]
...
[677  40]
.
[214  87]
....................
[252  53]
........
[ 84 160]
...
[100 122]
................
[103 138]
.................
[900  17]
.....................
[169  70]
.
[2231    7]
....
[517  37]
.
[ 71 126]
........
[80 99]
.....
[197  48]
.............
[ 88 118]
..................................
[ 65 101]
..............
[71 87]
..
[136  64]
..
[701  15]
..............
[1634    7]
....
[159  45]
.
[394  30]
.
[ 76 102]
...................
[60 90]
......................
[59 80]
.......................
[111  55]
.....
[71 86]
....
[56 79]
............
[128  39]
...........
[551  14]
....
[53 75]
.
[302  29]
....
[1197    7]
................
[52 71]
...................
[65 77]
..............
[89 49]
...
[47 66]
.......
[49 65]
..............
[111  36]
.......................
[49 59]
........
[58 74]
.....
[44 62]
.........
[232  28]
...........
[48 56]
.
[434  13]
.......
[904   6]
................./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[74 45]
......
[44 54]
........
[53 66]
....
[95 33]
.....................
[40 52]
........................
[50 60]
......
[40 50]
............
[182  26]
.....
[63 43]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
............
[86 30]
.
[49 55]
...
[657   6]
.
[363  12]
.......................
[49 53]
.....................
[56 38]
..
[48 51]
............./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[75 29]
...
[149  24]
.........................
[50 36]
.
[509   6]
...
[291  12]
.......
[70 27]
.......................
[121  22]
.
[46 36]
............
[63 24]
.....................
[44 35]
.......
[385   6]
....
[241  11]
...
[59 24]
................
[99 20]
.
[42 35]
..................
[57 24]
...........
[39 35]
......................
[56 24]
....
[37 35]
.................
[305   6]
.....
[37 34]
..
[214  10]
..
[84 17]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[53 23]
.................
[52 23]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..............
[77 14]
......
[237   6]
..
[184  10]
................
[68 14]
................
[196   5]
..
[157  10]
......
[55 13]
......................
[43 13]
......
[162   5]
..
[137   9]
..............
[42 13]
....................
[41 13]
...
[128   5]
..
[122   9]
..............
[39 13]
..................
[38 13]
............
[100   5]
.
[108   9]
...
[37 13]
................
[36 13]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[90  8]
...
[84  5]
................
[82  8]
.....
[75  5]
.............
[76  8]
..........
[68  4]
........
[72  8]
...............
[63  4]
...
[67  8]
.................
[62  8]
....
[58  4]
............
[60  8]
.............
[53  4]
....
[60  8]
................
[59  8]
......
[52  4]
..........
[59  8]
...............
[58  8]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[45  4]
..........
[42  4]
..........
[41  4]
..........
[40  4]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
No 1 0
Done
