Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367440): Gdk-CRITICAL **: 09:29:43.629: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367468): Gdk-CRITICAL **: 09:29:43.886: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367448): Gdk-CRITICAL **: 09:29:43.918: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367525): Gdk-CRITICAL **: 09:29:43.947: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367500): Gdk-CRITICAL **: 09:29:43.995: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367488): Gdk-CRITICAL **: 09:29:44.006: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367546): Gdk-CRITICAL **: 09:29:44.170: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3367556): Gdk-CRITICAL **: 09:29:44.185: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367582): Gdk-CRITICAL **: 09:29:44.199: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367574): Gdk-CRITICAL **: 09:29:44.206: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
................................................................
[4738 9439]
.
[4823 9458]
.
[4685 9480]
.
[4657 9406]
.
[4703 9461]
.
[4669 9440]
.
[4691 9456]
................................................................
[2219 8880]
.
[2330 8901]
.
[2302 8887]
.
[2270 8919]
.
[2239 8950]
.
[2214 8856]
.
[2234 8931]
................................................................
[1164 8283]
.
[1192 8354]
.
[1075 8313]
.
[1129 8376]
.
[1142 8380]
.
[1070 8267]
.
[1130 8407]
................................................................
[ 610 7682]
.
[ 572 7691]
.
[ 631 7778]
.
[ 588 7791]
.
[ 613 7771]
.
[ 559 7681]
.
[ 607 7806]
...............................................................
[ 350 7063]
.
[ 322 7052]
..
[ 376 7151]
.
[ 349 7139]
.
[ 326 7177]
.
[ 305 7041]
...
[ 337 7170]
...........................................................
[ 199 6482]
...
[ 220 6518]
.
[ 198 6229]
..
[ 204 6535]
..
[ 203 6522]
.
[ 187 6473]
....
[ 198 6559]
.....................................................
[ 130 5870]
....
[ 134 5946]
....
[ 137 5905]
....
[ 133 5898]
.
[ 139 5914]
...
[ 134 5960]
.....
[ 153 4875]
...........................................
[  87 5219]
......
[  97 5303]
....
[  96 5272]
......
[  91 5283]
....
[ 100 5234]
.
[  96 5421]
......................................
[ 113 3301]
...
[  65 4616]
........
[  73 4663]
.
[  73 4628]
..........
[  70 4646]
......
[  76 4816]
.........
[  69 4456]
.........................
[  47 4014]
..........
[  58 3986]
....
[  59 4024]
...........
[  55 4034]
..........
[  56 4201]
.....................
[  56 3519]
.
[  41 3420]
..........
[  53 3369]
...........
[  47 3327]
........
[  49 3427]
.........
[ 101 2066]
.......
[  50 3617]
.....
[  35 2856]
...............
[  48 2689]
.................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[  45 2543]
..
[  46 2817]
.................
[  52 2547]
..
[  43 3026]
.....
[  48 1935]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[  42 1839]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[  41 2431]

Data Dump...
............
[  40 1294]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[  48 1779]
........
[  91 1318]
......
[  46 1209]
.............
[ 41 857]
.............
[ 39 625]
............
[ 37 506]
.....
[ 77 819]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[ 67 546]
..........
[ 62 383]
..........
[ 59 272]
..........
[ 56 223]
..........
[ 53 174]
..........
[ 50 152]
..........
[ 42 127]
..........
[ 35 116]
..........
[ 33 111]
..........
[ 31 102]
..........
[27 88]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
High 1 7
Done
