Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317906): Gdk-CRITICAL **: 00:59:41.070: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317746): Gdk-CRITICAL **: 00:59:42.341: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317755): Gdk-CRITICAL **: 00:59:42.515: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317787): Gdk-CRITICAL **: 00:59:43.184: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317836): Gdk-CRITICAL **: 00:59:43.187: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317797): Gdk-CRITICAL **: 00:59:43.196: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317875): Gdk-CRITICAL **: 00:59:43.207: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317816): Gdk-CRITICAL **: 00:59:43.210: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317863): Gdk-CRITICAL **: 00:59:43.215: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317897): Gdk-CRITICAL **: 00:59:43.218: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4707 9773]
.
[4703 9730]
.
[4761 9765]
.
[4716 9767]
.
[4705 9775]
.
[4681 9762]
.
[4670 9768]
.
[4705 9736]
.
[4710 9759]
..................................................................................
[2322 9535]
.
[2253 9499]
.
[2286 9519]
.
[2279 9553]
.
[2274 9520]
.
[2200 9519]
.
[2212 9509]
.
[2317 9534]
.
[2260 9499]
..................................................................................
[1174 9295]
.
[1151 9245]
.
[1193 9285]
.
[1147 9312]
.
[1111 9291]
.
[1170 9309]
.
[1115 9279]
.
[1107 9233]
.
[1120 9262]
.................................................................................
[ 634 8989]
.
[ 617 9022]
..
[ 633 9052]
.
[ 609 9047]
.
[ 573 9044]
.
[ 611 9062]
.
[ 583 9039]
.
[ 605 8973]
...
[ 570 9007]
.............................................................................
[ 344 8737]
...
[ 372 8743]
.
[ 340 8742]
.
[ 337 8815]
.
[ 321 8800]
..
[ 327 8793]
..
[ 315 8786]
.
[ 324 8756]
......
[ 327 8778]
....................................................................
[ 202 8485]
....
[ 222 8501]
......
[ 222 8551]
.
[ 209 8549]
.
[ 203 8471]
...
[ 195 8489]
.
[ 185 8493]
.
[ 198 7904]
.......
[ 193 8536]
..........................................................
[ 138 8200]
.......
[ 141 8229]
.......
[ 152 8285]
.....
[ 142 8258]
.
[ 123 8238]
...
[ 116 8089]
.
[ 132 7773]
...........
[ 122 8297]
......................
[ 146 5689]
.........................
[ 100 7633]
...
[ 103 7933]
........
[ 100 8033]
...........
[  82 7981]
...
[ 100 7804]
.....
[  81 7166]
........
[  99 8038]
.................
[ 106 5810]
....................
[  72 7637]
.........
[  76 7766]
...
[  86 5911]
.............
[  58 7654]
...........
[  76 6847]
....
[  75 7764]
....................
[ 127 3413]
......
[  64 5456]
..
[  57 7088]
..
[  63 7504]
.........................
[  52 7071]
..........
[  63 7540]
.................
[  55 7234]
..........
[  94 3686]
...
[  49 5865]
..
[  64 5079]
...
[  78 3777]
..................
[  49 7312]
........
[  49 7007]
.....
[  45 5755]
.........................
[  46 6755]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[  44 7046]
..........
[  58 3607]
..........
[  46 4125]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[  44 6776]

Data Dump...
...................
[  43 3933]
..
[ 109 2006]
.
[  62 3317]
..............
[  75 2288]
........
[  83 2211]
....
[  45 2579]
.....................
[  42 2441]
..
[  49 2294]
......................
[  53 2017]
.....
[  44 1633]
..................
[  69 1373]
....
[  39 1478]
........
[ 101 1203]
.....
[  78 1343]
............
[  42 1015]
......
[  47 1434]
..............
[  51 1269]
......
[ 38 934]
...................
[ 40 678]
........
[ 66 859]
.......................
[ 36 604]
....
[ 75 815]
......
[ 40 464]
...
[ 44 939]
...
[ 95 721]
..
[ 49 825]
.............................
[ 40 356]
....
[ 34 413]
..................
[ 63 515]
........
[ 38 293]
.......................
[ 36 261]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[ 33 290]
.
[ 48 559]
........
[ 43 603]
......
[ 73 491]
.............
[ 31 224]
................
[ 84 428]
.......
[ 28 185]
..........
[ 61 341]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[ 47 390]
...............
[ 42 414]
..............
[ 68 332]
........
[ 44 284]
........
[ 60 236]
.................
[ 73 265]
.
[ 42 278]
.......
[ 42 224]
........................
[ 64 228]
...
[ 58 173]
....
[ 41 176]
..........
[ 38 205]
..................
[ 40 147]
...............
[ 66 180]
.........
[ 56 131]
..
[ 38 131]
......
[ 36 153]
.......
[ 57 155]
........
[ 36 124]
................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[ 36 119]

Data Dump...
.............
[ 35 124]
.
[ 56 104]
....................
[ 65 116]
...
[ 55 111]
.....
[ 33 109]
.......
[54 86]
...................
[32 95]
.................
[53 75]
......
[31 90]
..
[53 88]
.........
[62 91]
............
[30 81]
.........
[51 68]
..........
[29 76]
............/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[46 63]
.
[50 74]
.................
[46 61]
.
[58 68]
.................
[45 58]
.....
[49 68]
...........
[41 58]
..............
[41 57]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[55 58]
..
[47 60]
.................
[46 53]
.......
[52 47]
.........
[43 48]
...............
[41 44]
....
[50 43]
...........
[40 40]
...............
[39 39]
.....
[46 36]
.........
[38 39]
..............
[38 37]
............
[36 37]
......
[44 34]
.......
[36 37]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[42 33]
..........
[42 31]
..........
[42 30]
..........
[40 29]
..........
[38 29]
..........
[38 29]
..........
[38 29]
..........
[37 28]
..........
[36 28]
..........
[36 27]
..........
[35 27]
..........
[34 27]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[34 27]

Data Dump...
High 1 3
Done
