Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122418): Gdk-CRITICAL **: 01:01:08.895: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122438): Gdk-CRITICAL **: 01:01:08.952: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122456): Gdk-CRITICAL **: 01:01:08.990: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122420): Gdk-CRITICAL **: 01:01:09.023: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122540): Gdk-CRITICAL **: 01:01:09.202: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122466): Gdk-CRITICAL **: 01:01:09.208: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122524): Gdk-CRITICAL **: 01:01:09.210: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4122492): Gdk-CRITICAL **: 01:01:09.229: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122510): Gdk-CRITICAL **: 01:01:09.233: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122543): Gdk-CRITICAL **: 01:01:09.254: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4748 9501]
.
[4700 9512]
.
[4907 9170]
.
[5087 8845]
.
[9607 4633]
.
[9762 4580]
.
[9123 4839]
.
[9695 4551]
..
[5796 7740]
.........................................................................
[2298 8992]
...
[2253 9012]
.......
[2506 8100]
..
[9216 2170]
.
[9518 2164]
.
[2688 7723]
..
[9413 2099]
..
[8226 2491]
..........
[3582 5696]
..................................................
[1174 8498]
.....
[1156 8425]
...............
[8796 1093]
....
[9238 1053]
..
[1332 6826]
....
[1468 6438]
..
[9120 1030]
....
[7150 1347]
..........................
[2307 4055]
.............
[ 618 8041]
......
[ 629 7771]
.........................
[8332  563]
.....
[8965  533]
...........
[ 770 5517]
.
[8820  558]
...
[ 836 5183]
.............
[6032  753]
......
[ 357 7556]
.............
[ 345 7010]
.....................
[1579 2810]
..........
[7769  333]
...........
[8716  306]
..........
[ 216 7031]
..
[8458  282]
.............
[ 471 4195]
.....
[ 535 4036]
....
[ 227 6059]
.................
[4859  458]
..................
[ 149 6496]
......
[7138  199]
.........
[8468  180]
....................
[1106 1941]
.
[8131  171]
.......
[ 156 4995]
..........
[ 107 5994]
................
[ 322 3073]
.
[ 352 3042]
........................
[6428  123]
....
[3797  329]
.
[  79 5442]
...
[8217  103]
.....................
[ 122 3925]
............
[7729   98]
.....
[  60 4965]
...............................
[ 789 1365]
....
[  51 4448]
.....
[ 242 2225]
..........
[ 228 2158]
....
[7949   67]
....
[5597   86]
....
[  45 3923]
..................
[  96 2907]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
............
[2887  217]
.......
[7278   63]
...........................
[7679   48]
.........
[ 176 1616]
.....
[4676   64]
..
[  76 2063]
...
[ 172 1521]
..
[567 937]
....................................
[6748   37]
......
[7409   29]
.....
[2163  159]
..........
[  64 1454]
.............
[ 137 1224]
....
[3784   48]
..........
[ 136 1059]
..................
[421 667]
...
[7150   17]
.........
[  60 1035]
...........
[6144   27]
........................
[1574  120]
..
[104 884]
........
[2920   39]
........
[ 54 754]
..
[6858   13]
......
[102 740]
.............................
[317 476]
.....
[ 49 533]
...............
[5506   26]
.....
[ 82 626]
...........
[6580   10]
.......
[ 46 409]
.........
[2195   35]
........
[1149   92]
......
[ 81 521]
........
[ 41 314]
...................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[ 70 482]
..
[6308    8]
.........
[234 365]
....................
[4860   20]
...........
[ 59 393]
...
[1646   31]
......
[ 57 348]
...
[6044    8]
.........
[843  74]
...........................
[ 52 280]
..........
[192 280]
.........
[ 54 308]
...
[5786    6]
...........
[ 44 224]
............
[1191   27]
.........
[4204   18]
.....
[ 39 179]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.................
[5549    6]
.
[ 48 239]
..
[623  63]
................
[151 222]
...................
[ 42 197]
.....
[5281    6]
..
[909  24]
........................
[ 39 154]
..............
[3573   18]
.........
[5016    6]
.
[ 34 125]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[125 172]
....
[469  51]
.................
[668  21]
.......
[4749    6]
....................
[106 143]
..........
[4471    6]
..............
[360  39]
..
[519  20]
............
[4174    6]
.
[2994   13]
...
[ 93 121]
........................
[3904    6]
..............
[ 78 101]
....
[394  19]
.........
[3643    6]
............
[282  31]
........
[63 91]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[3394    6]

Data Dump...
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[300  19]
...............
[2476   11]
..
[239  29]
..
[238  17]
...................
[201  14]
............/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[193  26]
.............
[170  23]
............
[2027   11]
.
[150  23]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[1653    9]
..........
[1341    8]
..........
[1087    8]
..........
[884   8]
..........
[711   7]
..........
[574   7]
..........
[490   7]
..........
[401   7]
..........
[338   6]
..........
[286   6]
..........
[238   6]
..........
[213   6]
..........
[196   6]
..........
[177   6]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
No 1 6
Done
