Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121835): Gdk-CRITICAL **: 01:01:00.986: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121842): Gdk-CRITICAL **: 01:01:01.007: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121912): Gdk-CRITICAL **: 01:01:01.071: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121852): Gdk-CRITICAL **: 01:01:01.100: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121893): Gdk-CRITICAL **: 01:01:01.141: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121936): Gdk-CRITICAL **: 01:01:01.148: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121973): Gdk-CRITICAL **: 01:01:01.176: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121954): Gdk-CRITICAL **: 01:01:01.242: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121999): Gdk-CRITICAL **: 01:01:01.258: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122012): Gdk-CRITICAL **: 01:01:01.357: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4744 9757]
.
[4741 9749]
.
[4847 9640]
.
[4766 9693]
.
[4642 9760]
.
[4734 9767]
.
[4725 9600]
.
[4924 9367]
.
[5516 8259]
...............................................................................
[2280 9538]
.
[2323 9459]
..
[2229 9519]
.
[2231 9431]
.
[2211 9510]
..
[2458 8547]
...
[2651 8171]
..
[2678 8077]
...............
[3583 5868]
.......................................................
[1118 9277]
.
[1108 9273]
.
[1186 9165]
..
[1142 9110]
.
[1111 9212]
.....................
[1502 6635]
....
[1594 6302]
....
[1777 5788]
...............................
[2524 3821]
...........
[ 580 9016]
.
[ 572 9050]
..
[ 613 8784]
...
[ 597 8693]
.
[ 606 8889]
.......................................................
[1028 4609]
........
[1084 4536]
.
[ 330 8730]
..
[ 316 8793]
.......
[ 365 8134]
..
[1298 3653]
.
[ 353 8415]
.
[ 350 8111]
...................................
[1865 2517]
..................
[ 212 8414]
.
[ 190 8532]
...................
[ 206 7118]
..
[ 209 7660]
..
[ 221 7179]
.................................
[ 789 2969]
...
[ 797 3126]
.
[ 148 8047]
.
[ 132 8270]
........................
[1006 2254]
.............
[ 155 6648]
.......
[ 147 5652]
....
[ 167 5892]
..
[  83 8010]
...
[ 112 7459]
...........
[1377 1597]
...................................
[  61 7710]
.........
[  81 6391]
............
[ 120 5320]
................
[  46 7465]
.
[ 596 2063]
.....
[ 605 1892]
..
[ 125 4431]
.
[ 114 4149]
........................
[  41 7216]
........
[  66 4849]
....
[ 806 1420]
..............
[  39 6952]
......................
[  39 6690]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[  91 3967]
...
[1016 1032]
.....................
[ 100 3094]
.
[  59 3348]
...
[  81 2827]
.....................
[ 446 1392]
........
[ 465 1226]
.........
[  75 2837]
...............
[  53 2180]
......
[670 878]
...........
[  85 2101]
...
[  68 1880]
.....
[767 673]
..........................
[  64 1968]
...
[  52 1402]
........
[343 929]
.................
[387 789]
..........
[  71 1389]
.....
[  58 1246]
............
[ 49 883]
........
[556 554]
..
[  62 1351]
............
[602 468]
.............................
[ 44 587]
..
[286 638]
.....
[ 58 961]
...
[ 52 843]
..............
[ 58 916]
......
[310 515]
................
[ 41 407]
.............................
[459 360]
......
[ 48 662]
...
[488 331]
.
[ 37 312]
.....
[ 52 635]
..
[ 49 571]
...................
[230 426]
.........
[ 37 249]
...............................
[ 34 202]
...
[252 349]
.
[ 51 454]
...........
[ 44 491]
.........
[ 31 178]
........
[ 44 411]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........................
[ 43 351]
.
[375 225]
...
[372 259]
.............
[181 285]
...
[ 43 359]
..............
[ 41 310]
..
[ 41 280]
..........................
[211 241]
........
[ 40 236]
..
[ 38 268]
.........................
[ 38 212]
.
[ 39 239]
.....................
[286 163]
.
[ 36 192]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[141 217]
.
[ 34 209]
...
[314 174]
....................
[ 36 187]
.........
[ 33 175]
.............
[181 169]
...............
[ 33 141]
...
[ 32 156]
.....................
[ 32 130]
.
[121 169]
.......
[231 113]
.............
[ 32 121]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[ 29 125]
.......
[263 119]
..............
[ 26 105]
..............
[152 126]
.....
[25 96]
..............
[107 123]
....
[22 92]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[187  84]
..............
[229  86]
..........
[125 100]
..
[89 91]
..............
[158  61]
...................
[78 72]
....
[192  65]
..
[110  75]
...............
[132  51]
...........
[67 61]
................
[96 61]
......
[156  52]
........
[117  42]
.
[60 51]
...........................
[57 50]
...
[84 50]
...........
[102  36]
...
[128  43]
...........
[50 44]
......................
[78 43]
...
[46 43]
......
[88 31]
.................
[43 40]
.
[112  31]
...................
[40 36]
.......
[70 41]
.......
[75 28]
.....
[39 35]
............/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..............
[94 27]
...
[70 21]
.
[62 37]
........................
[55 20]
....
[55 33]
....slurmstepd-phcompute006: error: *** JOB 810632 ON phcompute006 CANCELLED AT 2024-02-25T09:23:15 ***
