Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121833): Gdk-CRITICAL **: 01:01:00.982: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121841): Gdk-CRITICAL **: 01:01:01.055: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121858): Gdk-CRITICAL **: 01:01:01.071: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121887): Gdk-CRITICAL **: 01:01:01.106: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121913): Gdk-CRITICAL **: 01:01:01.131: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121929): Gdk-CRITICAL **: 01:01:01.195: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121949): Gdk-CRITICAL **: 01:01:01.198: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121965): Gdk-CRITICAL **: 01:01:01.207: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4121990): Gdk-CRITICAL **: 01:01:01.260: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4122008): Gdk-CRITICAL **: 01:01:01.268: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4697 9613]
.
[4715 9529]
.
[4651 9619]
.
[4730 9602]
.
[4697 9602]
.
[4679 9598]
.
[4642 9603]
.
[5187 8669]
.......
[6338 7058]
........................................................................
[2275 9227]
.
[2335 9084]
.
[2254 9242]
..
[2297 9102]
.
[2221 9193]
.
[2388 8647]
.
[2216 9190]
...............
[3162 6499]
.................
[5078 3970]
............................................
[1146 8809]
.
[1149 8846]
.
[1181 8675]
.
[1144 8483]
.
[1194 8444]
..
[1142 8642]
...........
[1379 6758]
.....................................
[2160 4420]
......................
[ 614 8378]
...
[ 619 8432]
...
[4197 2158]
..
[ 640 7951]
..
[ 639 7988]
..
[ 620 7597]
.
[ 658 7502]
......................................
[ 997 4563]
.........................
[ 320 7930]
.
[ 356 7988]
............
[ 364 7209]
...
[ 394 6792]
.....
[ 398 6374]
...
[ 390 6271]
.....
[1553 2977]
..................................
[3510 1189]
..
[ 213 7543]
.
[ 187 7477]
..........................
[ 235 6153]
.......
[ 751 2887]
...
[ 268 5259]
.........
[ 265 4935]
....
[ 242 4909]
............
[ 144 7115]
.
[ 132 6865]
....................................
[1158 1937]
..........
[ 155 4894]
...
[ 107 6634]
.........
[  82 6090]
..............
[ 199 3688]
.....
[2931  722]
....
[ 182 3575]
.....
[ 186 3628]
...............
[  77 6020]
....
[ 579 1763]
............
[  68 5066]
................
[ 125 3714]
............
[  66 5178]
...........................
[ 163 2482]
.....
[ 873 1260]
..
[  60 3864]
..
[ 140 2495]
......
[ 138 2554]
..
[  61 4168]
....................................
[ 100 2693]
..
[2467  430]
........
[  55 2992]
.......
[  55 2699]
.....
[ 473 1100]
...........................
[ 143 1657]
......
[  52 2025]
.
[ 115 1685]
..........
[ 112 1761]
.............
[  48 1838]
.........
[  79 1886]
.......
[684 859]
...
[  51 1343]
.......................................
[ 50 891]
......
[  47 1235]
..............
[2059  294]
..
[ 116 1084]
......
[  94 1107]
..
[388 706]
..
[ 49 659]
......
[  86 1229]
.......
[  68 1303]
...............
[ 44 521]
............./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[ 43 848]
...................................
[529 576]
.....
[ 39 632]
..........
[ 64 924]
...
[ 79 759]
....
[102 712]
..
[ 74 879]
..................
[ 36 478]
...................
[323 464]
...
[1696  190]
........
[ 35 397]
............
[ 58 673]
............
[ 31 340]
.........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[ 66 534]
..
[ 64 625]
....
[ 92 470]
............
[430 420]
....
[ 54 522]
.......................................
[ 47 389]
.
[ 57 481]
...
[ 56 369]
.
[266 315]
.............
[ 74 332]
....
[1420  133]
..........
[ 45 296]
.............................
[ 41 238]
..
[ 49 377]
.........
[ 47 259]
..
[341 290]
........
[ 38 209]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...........
[ 65 243]
.................
[ 45 290]
......
[216 218]
.
[ 41 201]
...........................
[ 41 229]
..
[ 56 193]
..
[1152   92]
...........
[ 39 156]
.............
[270 216]
.....
[ 36 176]
......................
[ 32 127]
......
[ 52 155]
.
[ 33 153]
......................./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[ 32 134]

Data Dump...
..
[183 159]
.....
[ 29 103]
...................
[26 91]
.
[ 50 131]
.............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[218 167]
..
[933  72]
......
[ 44 113]
...................
[ 41 100]
...
[157 115]
...............
[40 91]
..............
[38 80]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[183 127]
..........
[776  56]
.....
[136  91]
............
[152 102]
................
[120  76]
....
[653  46]
......
[124  80]
...................
[103  57]
.....
[109  70]
..........
[533  37]
..............
[92 47]
.
[98 60]
......................
[91 54]
......
[85 46]
..
[458  33]
.............
[81 51]
.................
[74 41]
...
[73 49]
...................
[62 49]
....
[384  25]
..........
[68 38]
..
[55 45]
................
[51 39]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[62 37]
............
[320  20]
..
[59 34]
.............
[54 30]
.............
[51 29]
.............
[49 29]
.....
[269  18]
......
[48 29]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[245  16]
..........
[210  15]
..........
[183  14]
..........
[166  14]
..........
[144  14]
..........
[124  14]
..........
[110  14]
..........
[103  14]
..........
[91 13]
..........
[82 11]
..........
[78 10]
..........
[71 10]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[66  9]

Data Dump...
Low 1 5
Done
