Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:12991): Gdk-CRITICAL **: 09:29:55.999: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:12998): Gdk-CRITICAL **: 09:29:56.056: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13029): Gdk-CRITICAL **: 09:29:56.154: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13015): Gdk-CRITICAL **: 09:29:56.170: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13039): Gdk-CRITICAL **: 09:29:56.220: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13051): Gdk-CRITICAL **: 09:29:56.247: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13077): Gdk-CRITICAL **: 09:29:56.276: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:13069): Gdk-CRITICAL **: 09:29:56.301: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13094): Gdk-CRITICAL **: 09:29:56.322: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13100): Gdk-CRITICAL **: 09:29:56.387: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...........................................................................................
[4712 9583]
.
[4849 9363]
.
[4625 9578]
.
[4693 9573]
.
[4665 9596]
.
[4686 9594]
.
[4621 9621]
.
[4652 9527]
.
[4967 9058]
.
[5405 8331]
........................................................................................
[2226 9162]
.
[2237 9185]
.
[2233 9171]
.
[2286 8982]
.
[2302 9108]
.
[2210 9205]
..
[2261 8932]
.
[2547 8208]
............
[3064 6764]
...........
[3875 5283]
...........................................................
[1085 8749]
..
[1104 8724]
.
[1132 8802]
....
[1118 8740]
...
[1227 8205]
..
[1224 8077]
..
[1175 8103]
............
[1452 6605]
...............................
[2190 4404]
......................
[3027 3045]
........
[ 570 8310]
.
[ 593 8307]
..
[ 602 8381]
......
[ 572 8311]
..............
[ 724 6714]
...
[ 753 6640]
..
[ 665 6940]
...........................
[ 960 4904]
.....................
[ 335 7827]
...
[ 321 7867]
........
[ 336 7914]
..
[ 319 7824]
...........................
[1632 2735]
.................
[ 429 5503]
..
[ 528 4952]
.
[ 525 4825]
.........
[2448 1746]
......
[ 205 7411]
..
[ 212 7420]
.............
[ 217 7299]
..
[ 189 7286]
.................
[ 680 3454]
...............................
[ 141 6954]
.......
[ 133 6895]
....................
[ 141 6470]
.
[ 296 4084]
..
[ 135 6567]
.................
[ 377 3413]
...
[ 396 3200]
.........
[1291 1702]
..
[  94 6485]
.........
[  83 6270]
.........................
[2001 1029]
.........
[  94 5506]
...
[ 101 5280]
...
[ 504 2328]
........
[  70 5785]
..............
[  59 5456]
....................
[ 224 2886]
..................
[  60 4876]
...............
[ 296 2263]
..
[  73 4276]
..
[ 327 2058]
....
[  46 4419]
.
[  84 3967]
............................
[  53 3682]
..
[1018 1050]
.............................
[  40 3276]
....
[ 394 1562]
........
[1650  614]
.....
[  61 3070]
....
[  49 2553]
......
[ 177 1952]
.
[  73 2745]
.................................
[  39 2312]
..........
[ 238 1423]
..
[  48 1704]
......
[ 276 1316]
......................
[  53 2144]
...................
[  67 1846]
.
[  39 1560]
...
[  48 1119]
................
[808 690]
.......
[ 323 1066]
......
[ 144 1339]
...............
[ 42 777]
....
[  38 1057]
...................
[  46 1473]
...
[1381  379]
............
[ 38 571]
..............
[  64 1291]
...
[ 35 747]
......
[197 938]
...........
[236 863]
.
[ 33 432]
.........................
[ 33 540]
......................
[  42 1000]
..
[ 28 426]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[125 902]
........
[268 733]
...
[ 58 873]
...........
[648 442]
..................
[ 41 701]
.................
[169 629]
....
[ 49 603]
..
[1165  234]
.
[191 578]
..................
[ 41 519]
.....
[106 625]
....................
[215 535]
..
[ 44 442]
............
[ 37 386]
.................................
[ 43 329]
.
[ 33 308]
.
[540 296]
.........
[147 424]
..................
[ 29 263]
....
[154 404]
......
[ 92 447]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[ 41 264]
......................
[932 155]
.
[ 37 222]
...
[175 394]
.............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....................
[ 76 315]
.
[130 303]
..........
[132 291]
..
[445 217]
..............
[150 284]
................
[ 63 249]
........
[765 114]
......
[111 211]
................
[115 207]
.........
[ 58 200]
.
[126 223]
............
[371 155]
.....................
[100 159]
...
[ 51 154]
................
[102 156]
...
[115 169]
.........
[649  83]
.....
[ 47 123]
........................
[ 89 125]
....
[ 42 106]
............
[303 111]
....
[100 143]
..........
[33 92]
....
[ 88 125]
................/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[32 82]

Data Dump...
.............
[ 77 108]
......
[ 90 120]
............
[550  58]
........
[81 99]
.............
[ 80 103]
.
[68 93]
....
[254  88]
.........................
[73 91]
.......
[74 85]
....
[60 79]
................
[64 87]
.........................
[61 79]
.
[52 69]
.
[462  45]
...........
[69 81]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[226  68]
...........
[49 66]
.....................
[63 70]
.
[42 60]
...................
[40 59]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[56 67]
.....
[199  58]
..
[394  38]
..........
[53 64]
................
[49 58]
...............
[46 54]
........./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[170  55]
.....
[338  28]
..............
[145  47]
.........
[298  21]
........
[118  40]
................
[249  18]
.
[106  37]
................
[90 35]
.........
[208  15]
.......
[78 30]
................
[70 27]
.....
[189  15]
..........
[56 26]
..............
[48 23]
..........
[168  15]
...
[44 22]
.............
[39 19]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[150  12]
..........
[130  11]
..........
[114   8]
..........
[100   8]
..........
[90  8]
..........
[79  7]
..........
[67  6]
..........
[62  6]
..........
[58  6]
..........
[54  6]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
Low 1 5
Done
slurmstepd-phcompute006: error: Detected 1 oom-kill event(s) in StepId=810879.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
