Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367417): Gdk-CRITICAL **: 09:29:43.551: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367457): Gdk-CRITICAL **: 09:29:43.577: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367412): Gdk-CRITICAL **: 09:29:43.606: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367447): Gdk-CRITICAL **: 09:29:43.649: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367486): Gdk-CRITICAL **: 09:29:43.718: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367523): Gdk-CRITICAL **: 09:29:43.779: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367560): Gdk-CRITICAL **: 09:29:43.784: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367508): Gdk-CRITICAL **: 09:29:43.787: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367548): Gdk-CRITICAL **: 09:29:43.794: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367581): Gdk-CRITICAL **: 09:29:43.871: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...........................................................................................
[4771 9499]
.
[4704 9511]
.
[4735 9536]
.
[4725 9515]
.
[4722 9522]
.
[4672 9546]
.
[4709 9544]
.
[4704 9520]
.
[4622 9543]
.
[4570 9596]
...........................................................................................
[2263 9029]
.
[2312 9049]
.
[2246 9027]
.
[2296 9057]
.
[2308 9064]
.
[2283 9058]
.
[2217 9059]
.
[2253 9043]
.
[2236 9072]
.
[2236 9144]
..........................................................................................
[1084 8567]
.
[1131 8507]
.
[1193 8567]
.
[1119 8532]
.
[1152 8571]
.
[1158 8573]
..
[1093 8603]
.
[1094 8587]
.
[1121 8544]
.......
[1147 8668]
...................................................................................
[ 636 8004]
..
[ 633 8058]
.
[ 551 8048]
.
[ 575 8053]
.
[ 610 8078]
.
[ 585 8058]
.
[ 595 8063]
.
[ 601 8103]
.....
[ 576 8040]
......
[ 631 8113]
...............................................................................
[ 360 7448]
..
[ 351 7566]
.
[ 329 7529]
..
[ 358 7564]
.
[ 339 7558]
..
[ 320 7565]
.
[ 324 7543]
..
[ 312 7611]
......
[ 325 7524]
.......
[ 344 7592]
......................................................................
[ 221 6939]
.......
[ 201 7055]
..
[ 213 7028]
..
[ 223 7069]
.
[ 223 7040]
.
[ 207 7043]
...
[ 184 7076]
..
[ 198 7137]
.......
[ 194 7003]
...........
[ 204 7071]
........................................................
[ 145 6344]
.............
[ 131 6546]
..
[ 155 6550]
.
[ 128 6470]
.
[ 147 6499]
...
[ 133 6520]
....
[ 117 6592]
.........
[ 142 6551]
.......
[ 128 6498]
...........
[ 129 6563]
............................................
[ 102 5720]
...............
[ 111 6009]
...
[  88 6001]
...
[  92 5784]
.
[  90 6035]
.
[ 114 5984]
...
[  92 6091]
........................
[ 105 5434]
.
[  87 5904]
........
[  88 5990]
.......................................
[  83 4922]
...
[  83 5494]
..........
[  68 5486]
.
[  68 5510]
...
[  83 5481]
........
[  64 5608]
.........
[  74 4720]
..................................
[  61 4964]
.
[  65 5377]
...............
[  66 5000]
............
[  55 4983]
.....
[  56 4919]
...
[  71 3857]
..
[  91 3750]
.
[  51 5039]
.
[  69 4956]
...................................................
[  59 4491]
............
[  39 4587]
.
[  66 3250]
..
[  45 4510]
..........
[  46 4547]
...
[  56 4423]
..
[  41 4148]
.......................
[  53 3628]
............
[  52 3997]
.........
[  67 2780]
......
[  41 4000]
....................
[  51 3905]
...
[  41 3993]
....................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[  39 3071]
......
[  35 3675]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[  46 3368]

Data Dump...
.......
[  40 3481]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..........
[  79 2357]
............
[  61 2055]
....
[  62 1892]
.......
[  34 2007]
.
[  45 2427]
.
[  33 2721]
.......................................
[  30 1300]
...
[  30 1867]
......
[  60 1245]
.......................
[  58 1351]
.....
[  43 1519]
..
[ 26 883]
.......
[  27 1254]
..
[  71 1449]
.............
[ 55 844]
..............
[ 25 654]
..............
[ 25 838]
....................
[ 22 518]
...
[ 53 609]
................
[ 24 607]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[ 55 874]
...
[ 41 992]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[ 48 443]
...................
[ 43 377]
.....
[ 70 936]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[ 36 671]
.
[ 53 591]
.........................
[ 32 487]
..
[ 52 414]
....
[ 63 626]
...................
[ 31 364]
.....
[ 47 298]
..................
[ 31 290]
.....
[ 58 420]
....
[ 47 234]
.............
[ 28 243]
................
[ 44 197]
....
[ 25 211]
..................
[ 21 188]
..........
[ 52 298]
.
[ 41 183]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
............
[ 38 173]
.............
[ 35 161]
............
[ 29 153]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[ 50 228]
..........
[ 42 166]
..........
[ 41 132]
..........
[ 37 111]
..........
[34 98]
..........
[31 88]
..........
[29 80]
..........
[27 74]
..........
[26 69]
..........
[24 64]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
High 1 6
Done
slurmstepd-phcompute025: error: Detected 1 oom-kill event(s) in StepId=810870.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
