Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13464): Gdk-CRITICAL **: 09:30:07.976: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13466): Gdk-CRITICAL **: 09:30:08.007: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13487): Gdk-CRITICAL **: 09:30:08.131: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13541): Gdk-CRITICAL **: 09:30:08.169: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13524): Gdk-CRITICAL **: 09:30:08.186: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13552): Gdk-CRITICAL **: 09:30:08.237: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13591): Gdk-CRITICAL **: 09:30:08.298: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13605): Gdk-CRITICAL **: 09:30:08.310: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13622): Gdk-CRITICAL **: 09:30:08.354: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:13636): Gdk-CRITICAL **: 09:30:08.420: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.........................................................................
[9276 4716]
.
[9474 4677]
.
[7545 5890]
.
[9684 4535]
.
[9665 4590]
.
[6125 7134]
..
[8049 5419]
.
[8350 5287]
..............................................................
[8561 2318]
...
[8952 2281]
........
[9335 2152]
.....
[9371 2131]
.
[5171 3771]
....
[3969 4923]
.
[7087 2726]
.
[6476 2976]
.........................................
[7810 1173]
..........
[8386 1146]
................
[8963 1070]
..
[9059 1093]
...............
[3500 2532]
.....
[5880 1507]
.
[2650 3321]
..
[5105 1694]
............
[7057  618]
...............
[7817  607]
........................
[8576  559]
......
[8743  588]
.............
[6300  343]
...............
[2326 1728]
.......
[7238  354]
.
[4760  860]
...
[1747 2248]
...
[3942 1032]
.....................
[5542  219]
.......
[8220  324]
..........
[8387  307]
...................
[6667  211]
...........
[4787  155]
..................
[1516 1225]
..................
[1206 1498]
.
[3776  519]
.
[7854  184]
..
[4001  106]
....
[3003  661]
..........
[6098  124]
....
[8029  183]
..............
[3216   82]
................................
[2400   72]
.....................
[1590   68]
..
[5526   89]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[7535  106]
.
[1032  878]
....................
[ 842 1037]
..
[7687  118]
....
[2901  328]
.....
[2206  451]
......
[4934   70]
.......................
[7198   62]
.................
[709 661]
.
[4382   53]
..................
[7282   70]
............
[617 741]
......
[3810   40]
.......
[2177  222]
.....
[6855   44]
.
[1608  299]
......................
[3224   37]
.......
[497 503]
.....................
[2643   37]
..
[6879   52]
................
[6489   31]
......
[456 520]
..
[2040   32]
.....................
[1466   32]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.......
[351 396]
..
[1704  157]
.
[1183  214]
.....................
[6155   25]
...
[6390   39]
...............
[324 386]
..
[255 309]
..................................
[5799   20]
..
[861 149]
..
[186 227]
.
[1301  115]
.............
[5923   26]
........
[240 277]
.......
[142 172]
.....................
[ 97 113]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[5455   17]
.................
[186 199]
.....
[647 112]
....
[980  89]
....
[5387   20]
.........
[5097   14]
.............
[150 151]
.............................
[4759   13]
.
[119 112]
....
[487  87]
.............
[4845   13]
...
[743  69]
...
[92 82]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.............
[4405   11]
...............
[371  67]
.............
[4058    9]
.
[4324   10]
...
[552  54]
......................
[282  52]
..
[3713    8]
...........................
[426  49]
.
[3368    8]
..
[3782    8]
...
[223  39]
.........................
[2984    7]
....
[170  35]
..................
[337  42]
.......
[123  31]
....
[2641    7]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[3305    8]
.......
[2278    7]
........
[260  36]
...........
[1908    7]
..................
[1578    7]
...
[203  30]
...............
[1216    7]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[2847    5]
...
[142  23]
............
[92 16]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[2404    4]
..........
[2006    4]
..........
[1672    4]
..........
[1356    4]
..........
[1126    4]
..........
[915   3]
..........
[739   3]
..........
[579   3]
..........
[446   3]
..........
[326   2]
..........
[203   2]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
No 1 8
Done
