Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367407): Gdk-CRITICAL **: 09:29:43.473: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367415): Gdk-CRITICAL **: 09:29:43.495: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367484): Gdk-CRITICAL **: 09:29:43.620: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367462): Gdk-CRITICAL **: 09:29:43.627: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367444): Gdk-CRITICAL **: 09:29:43.638: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367496): Gdk-CRITICAL **: 09:29:43.723: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367565): Gdk-CRITICAL **: 09:29:43.741: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367528): Gdk-CRITICAL **: 09:29:43.749: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367534): Gdk-CRITICAL **: 09:29:43.804: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3367576): Gdk-CRITICAL **: 09:29:43.821: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...........................................................................................
[4700 9671]
.
[4719 9652]
.
[4724 9670]
.
[4694 9679]
.
[4690 9682]
.
[4736 9673]
.
[4709 9698]
.
[4705 9691]
.
[4642 9690]
.
[4658 9699]
...........................................................................................
[2264 9327]
.
[2289 9358]
.
[2289 9338]
.
[2257 9290]
.
[2261 9371]
.
[2261 9365]
.
[2249 9333]
.
[2193 9401]
.
[2254 9365]
.
[2276 9349]
...........................................................................................
[1165 8997]
.
[1104 9035]
.
[1132 9017]
.
[1167 9065]
.
[1144 8959]
.
[1132 9038]
.
[1095 9042]
.
[1148 8997]
.
[1132 9029]
.
[1119 9021]
..........................................................................................
[ 584 8700]
..
[ 620 8677]
.
[ 583 8673]
.
[ 603 8735]
.
[ 616 8693]
.
[ 636 8648]
.
[ 615 8619]
.
[ 601 8706]
.
[ 584 8688]
...
[ 616 8683]
....................................................................................
[ 323 8353]
.....
[ 315 8331]
.
[ 346 8339]
.
[ 338 8399]
..
[ 360 8321]
..
[ 349 8274]
.
[ 317 8331]
.
[ 347 8284]
.
[ 340 8395]
....
[ 337 8332]
...............................................................................
[ 192 8018]
...
[ 185 7987]
.
[ 197 7977]
...
[ 195 8063]
........
[ 182 7957]
.
[ 215 7958]
..
[ 224 7771]
.
[ 199 8054]
..
[ 185 8000]
.
[ 219 7756]
......................................................................
[ 135 7671]
.....
[ 123 7628]
..
[ 112 7647]
.
[ 127 7704]
.............
[ 144 7625]
..
[ 121 7498]
.......
[ 127 7702]
....
[ 123 7580]
...
[ 161 6966]
...............
[ 142 6449]
....................................
[  88 7230]
......
[  88 7296]
........
[  73 7286]
...
[  94 7330]
............
[ 101 7280]
.....
[  89 6744]
........
[  97 7287]
...
[  83 6839]
............................
[ 121 5722]
............
[  65 6949]
......
[  66 6323]
...........
[  50 6973]
....
[  71 6894]
.............
[  79 6821]
...
[ 119 4397]
......................
[  72 6701]
.....
[  76 5317]
.......
[  59 6593]
...
[  61 5363]
................
[  41 6615]
..........
[  59 6237]
............
[  51 4479]
........
[  59 5976]
............
[  51 6202]
.
[  99 4278]
.....................
[  32 6289]
.......
[  58 5683]
.........................
[  46 5464]
..
[  53 4910]
............
[  30 5951]
...........
[  64 3677]
.........
[  52 4339]
.....
[  56 3630]
........
[  30 5599]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[ 109 2750]
.......
[  43 3747]
......
[  44 2749]
.........
[  54 4302]
..................
[  81 2956]
..............
[  40 2234]
....
[  50 2773]
........................
[  56 2326]
........
[  48 2963]
....
[  53 2322]
.....
[  40 1365]
........
[  44 1685]
...............
[  94 1655]
...........
[  47 1723]
......
[  73 2003]
...
[ 34 846]
....................
[  46 1938]
.................
[ 34 551]
..
[  53 1453]
...................
[  49 1489]
........
[  46 1090]
.
[  41 1025]
.
[ 30 401]
...................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
....
[  44 1237]
.........
[  66 1343]
....
[ 83 986]
.......................
[ 46 697]
..
[ 50 953]
.............
[ 40 833]
.....
[ 40 665]
.
[ 47 939]
..............................
[ 59 895]
..
[ 45 469]
..........
[ 38 592]
................
[ 76 642]
...
[ 45 621]
..................
[ 39 453]
....
[ 33 428]
.
[ 45 338]
...
[ 45 603]
.......................
[ 58 613]
.............
[ 31 326]
............
[ 42 268]
..............
[ 41 416]
....
[ 29 267]
............./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[ 38 327]
........
[ 41 226]
....
[ 43 400]
.....
[ 71 422]
....
[ 53 418]
..............
[ 41 202]
....................
[ 39 310]
....
[ 41 183]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[ 36 246]
........
[ 48 302]
........
[ 40 267]
................
[ 36 233]
..........
[ 69 287]
......
[ 36 189]
.
[ 47 231]
...................
[ 38 197]
..........
[ 34 175]
.....
[ 44 188]
..................
[ 36 148]
..............
[ 44 162]
......
[ 31 143]
........
[ 38 144]
.......
[ 65 207]
.....
[ 40 141]
............../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....
[ 36 116]
...
[ 27 124]
....................
[ 35 109]
....
[ 25 114]
.............
[ 32 101]
..........
[ 25 112]
............/home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[34 90]
.
[ 60 155]
.....
[30 93]
.....................
[30 81]
.
[29 83]
.....................
[28 82]
....
[30 68]
...............
[25 79]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[ 56 118]
...
[30 66]
............
[29 66]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.......
[55 91]
..........
[51 76]
..........
[45 67]
..........
[41 58]
..........
[38 51]
..........
[36 42]
..........
[36 41]
..........
[33 41]
..........
[33 40]
..........
[32 39]
......../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
High 1 4
Done
slurmstepd-phcompute025: error: Detected 1 oom-kill event(s) in StepId=810868.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
